### ISSUE TITLE
Cpu core 7 (prime core) restricted to 1.8ghz 

### ISSUE THREAD

**Issue by pranavsh1408** [YumeMichi/kernel_oneplus_sm8250#1]
the primary core (cpu7) the one clocked at 3.2 ghz(sd870) gets restricted to 1.8ghz only after the time device is ilde or gets in doze , if we reboot than cpu7 core work as expected, due to this the resource intensive task when done it does not perform as the way it shd. 
Kindly fix this problem .
see this screenshot for example.

this happens before reboot
https://ibb.co/0KkPcWK

this happens after reboot
https://ibb.co/n3GhjdB

**Comment by pranavsh1408** [comment]
Kindly fix this issue if possible many devs use your resources i didn't see this on aospa sd870 other devices

**Comment by YumeMichi** [comment]
> Kindly fix this issue if possible many devs use your resources i didn't see this on aospa sd870 other devices

Which branch are you using?

**Comment by YumeMichi** [comment]
@pranavcool007 Can you check again?

**Comment by pranavsh1408** [comment]
Will compile and check

**Comment by pranavsh1408** [comment]
Thanks dev , fixed
