### ISSUE TITLE
作者，帮忙看看这个报错吧

### ISSUE THREAD

**Issue by poxiao676** [YumeMichi/kernel_oneplus_sm8250#5]
[![Screenshot-20240126-113029-Net-Hunter-Terminal.png](https://i.postimg.cc/nLkh4bm8/Screenshot-20240126-113029-Net-Hunter-Terminal.png)](https://postimg.cc/Y4v77P88)

描述：在开启CONFIG_MODVERSIONS这个选项后就会出现这种情况，如果关闭则不会。

**Comment by YumeMichi** [comment]
为啥要开MODVERSIONS

**Comment by poxiao676** [comment]
> 为啥要开MODVERSIONS

为了加载某些编译模块

**Comment by YumeMichi** [comment]
你可以试一下从[arm64: cpufeature: add feature for CRC32 instructions](https://github.com/YumeMichi/kernel_oneplus_sm8250/commit/b264e99e22cb2d4850363aade1321f18f161423e)到[arm64: lib: Import latest version of Arm Optimized Routines' strncmp](https://github.com/YumeMichi/kernel_oneplus_sm8250/commit/189e855e69a7eb314a3e825e3664dd255819fc50)的提交都去掉，没有backport完全，不兼容MODVERSIONS

**Comment by poxiao676** [comment]
> 你可以试一下从[arm64: cpufeature: add feature for CRC32 instructions](https://github.com/YumeMichi/kernel_oneplus_sm8250/commit/b264e99e22cb2d4850363aade1321f18f161423e)到[arm64: lib: Import latest version of Arm Optimized Routines' strncmp](https://github.com/YumeMichi/kernel_oneplus_sm8250/commit/189e855e69a7eb314a3e825e3664dd255819fc50)的提交都去掉，没有backport完全，不兼容MODVERSIONS

OK 了，谢谢啦，那就先close
